## audio units found on R-Car
snd-soc-rcar-objs		:= sru_pcm.o
obj-$(CONFIG_SND_SOC_RCAR)	+= snd-soc-rcar.o

## boards
snd-soc-rcar-ak4643-objs	:= rcar_ak4643.o
obj-$(CONFIG_SND_RCAR_AK4643)	+= snd-soc-rcar-ak4643.o
